# Generated by Django 3.2.16 on 2024-03-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240321_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_user',
        ),
    ]
