# Generated by Django 3.2 on 2024-03-25 17:57

import django.core.validators
from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(reviews.models.get_current_year, message='Проверьте год выпуска!'), django.core.validators.MinValueValidator(-3000, message='Проверьте год выпуска!')], verbose_name='Год выпуска'),
        ),
    ]
